const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const STORAGE='json-lens-rule-lab-v1';let fields=[];let editingId=null;let lastResults=[];let errorsOnly=false;
const formats={
  any:{label:'任意文本',pattern:'.*',message:'允许任意值'},string:{label:'文本',pattern:'.+',message:'必须是非空文本'},number:{label:'数字',pattern:'^-?\\d+(\\.\\d+)?$',message:'必须是数字'},mobile:{label:'中国大陆手机号',pattern:'^1[3-9]\\d{9}$',message:'须为 11 位大陆手机号'},idcard:{label:'中国身份证号',pattern:'^[1-9]\\d{5}(18|19|20)\\d{2}(0[1-9]|1[0-2])(0[1-9]|[12]\\d|3[01])\\d{3}[0-9Xx]$',message:'须为有效的 18 位身份证格式'},name:{label:'中文姓名',pattern:'^[\\u4e00-\\u9fa5·]{2,20}$',message:'须为 2–20 位中文姓名'},email:{label:'邮箱',pattern:'^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$',message:'邮箱格式不正确'},date:{label:'日期 YYYY-MM-DD',pattern:'^\\d{4}-(0[1-9]|1[0-2])-([012]\\d|3[01])$',message:'须为 YYYY-MM-DD'},datetime:{label:'ISO 日期时间',pattern:'^\\d{4}-\\d{2}-\\d{2}[T ]\\d{2}:\\d{2}(:\\d{2})?',message:'须为 ISO 日期时间'},url:{label:'网址 URL',pattern:'^https?://.+',message:'须以 http:// 或 https:// 开头'},boolean:{label:'布尔值',pattern:'^(true|false)$',message:'须为 true 或 false'},enum:{label:'枚举',pattern:'',message:'值不在允许范围内'},custom:{label:'自定义正则',pattern:'.+',message:'不符合自定义格式'}
};
const sample={requestId:'REQ202607200001',user:{name:'张三',mobile:'13800138000',idCard:'11010119900307123X',email:'zhangsan@example.com',birthday:'1990-03-07'},channel:'APP',agreed:true};
const bad={requestId:'',user:{name:'John-123',mobile:'1280013800',idCard:'11010119901307123X',email:'zhangsan@example',birthday:'1990/03/07'},channel:'FAX',agreed:true};
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function savedRules(){try{return JSON.parse(localStorage.getItem(STORAGE)||'[]')}catch{return[]}}
function persist(list){localStorage.setItem(STORAGE,JSON.stringify(list));updateRuleCount()}
function updateRuleCount(){const list=savedRules();$('#ruleCount').textContent=list.length;renderLibrary();renderRuleSelect()}
function parseCsv(text){const lines=text.trim().split(/\r?\n/).filter(Boolean);if(lines.length<2)throw Error('CSV 至少需要表头和一行数据');const split=line=>line.split(/,(?=(?:[^"]*"[^"]*")*[^"]*$)/).map(x=>x.trim().replace(/^"|"$/g,''));const heads=split(lines[0]),vals=split(lines[1]);return Object.fromEntries(heads.map((h,i)=>[h,vals[i]??'']))}
function xmlNode(node){const children=[...node.children];if(!children.length)return node.textContent.trim();const out={};children.forEach(c=>{const val=xmlNode(c);if(c.tagName in out)out[c.tagName]=Array.isArray(out[c.tagName])?[...out[c.tagName],val]:[out[c.tagName],val];else out[c.tagName]=val});return out}
function parseText(text){const clean=text.trim();if(!clean)throw Error('内容为空');try{return {data:JSON.parse(clean),type:'JSON'}}catch{}if(/^</.test(clean)){const doc=new DOMParser().parseFromString(clean,'text/xml');if(doc.querySelector('parsererror'))throw Error('XML 格式不正确');return {data:{[doc.documentElement.tagName]:xmlNode(doc.documentElement)},type:'XML'}}if(clean.includes('\n')&&clean.split('\n')[0].includes(','))return {data:parseCsv(clean),type:'CSV'};const pairs=clean.split(/\r?\n/).map(l=>l.match(/^\s*([^:=]+)\s*[:=]\s*(.*)$/)).filter(Boolean);if(pairs.length)return {data:Object.fromEntries(pairs.map(m=>[m[1].trim(),m[2].trim()])),type:'键值文本'};throw Error('无法识别文档，请使用 JSON、CSV、XML 或 key=value 文本')}
function flatten(value,path='',out=[]){if(Array.isArray(value)){if(!value.length)out.push({path,value:[]});else flatten(value[0],path+'[0]',out)}else if(value&&typeof value==='object')Object.entries(value).forEach(([k,v])=>flatten(v,path?`${path}.${k}`:k,out));else out.push({path,value});return out}
function infer(path,value){const key=path.toLowerCase(),s=String(value??'');if(/mobile|phone|tel|手机号|电话/.test(key)||/^1[3-9]\d{9}$/.test(s))return'mobile';if(/idcard|identity|身份证|证件号/.test(key)||/^[1-9]\d{16}[0-9Xx]$/.test(s))return'idcard';if(/email|mail|邮箱/.test(key)||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s))return'email';if(/name|姓名|联系人/.test(key)&&/^[\u4e00-\u9fa5·]{2,20}$/.test(s))return'name';if(/birthday|date|日期|生日/.test(key)&&/^\d{4}-\d{2}-\d{2}$/.test(s))return'date';if(/time|时间/.test(key)&&/^\d{4}-\d{2}-\d{2}[T ]/.test(s))return'datetime';if(/url|link|地址/.test(key)&&/^https?:/.test(s))return'url';if(typeof value==='boolean')return'boolean';if(typeof value==='number')return'number';return'string'}
function analyze(text){const parsed=parseText(text);fields=flatten(parsed.data).map((f,i)=>({id:crypto.randomUUID?crypto.randomUUID():Date.now()+i,path:f.path,sample:f.value,format:infer(f.path,f.value),required:true,pattern:''}));editingId=null;$('#sourceType').textContent=parsed.type;$('#schemaStatus').textContent=`已解析 ${fields.length} 个叶子字段`;renderRules();}
function formatOptions(selected){return Object.entries(formats).map(([k,v])=>`<option value="${k}" ${k===selected?'selected':''}>${v.label}</option>`).join('')}
function renderRules(){const body=$('#rulesBody');if(!fields.length){body.innerHTML='<tr class="table-empty"><td colspan="5">导入样例后，将在这里生成可编辑规则</td></tr>';$('#saveRule').disabled=true;return}body.innerHTML=fields.map((f,i)=>`<tr data-id="${f.id}"><td><input class="field-path" type="text" value="${escapeHtml(f.path)}" aria-label="字段路径"></td><td class="sample-cell" title="${escapeHtml(JSON.stringify(f.sample))}">${escapeHtml(typeof f.sample==='string'?f.sample:JSON.stringify(f.sample))}</td><td><select class="field-format">${formatOptions(f.format)}</select><input class="field-pattern" type="text" value="${escapeHtml(f.pattern||formats[f.format].pattern)}" title="校验正则" aria-label="校验正则"></td><td><input class="field-required" type="checkbox" ${f.required?'checked':''} aria-label="必填"></td><td><button class="remove-rule" type="button" data-remove="${i}" aria-label="删除字段">×</button></td></tr>`).join('');$('#detectBadge').textContent=`已识别 ${fields.length} 个字段`;$('#detectBadge').classList.add('ready');$('#saveRule').disabled=false;bindRuleRows()}
function bindRuleRows(){$$('#rulesBody tr[data-id]').forEach((row,i)=>{row.querySelector('.field-format').onchange=e=>{fields[i].format=e.target.value;row.querySelector('.field-pattern').value=formats[e.target.value].pattern};row.querySelector('.field-path').oninput=e=>fields[i].path=e.target.value;row.querySelector('.field-pattern').oninput=e=>fields[i].pattern=e.target.value;row.querySelector('.field-required').onchange=e=>fields[i].required=e.target.checked});$$('[data-remove]').forEach(b=>b.onclick=()=>{fields.splice(+b.dataset.remove,1);renderRules()})}
function collectRows(){return $$('#rulesBody tr[data-id]').map(row=>({path:row.querySelector('.field-path').value.trim(),sample:fields.find(f=>String(f.id)===row.dataset.id)?.sample,format:row.querySelector('.field-format').value,pattern:row.querySelector('.field-pattern').value,required:row.querySelector('.field-required').checked}))}
function saveRule(){const name=$('#ruleName').value.trim();if(!name)return toast('请填写规则名称');const list=savedRules(),now=new Date().toISOString();const item={id:editingId||String(Date.now()),name,desc:$('#ruleDesc').value.trim(),fields:collectRows(),updatedAt:now};const at=list.findIndex(x=>x.id===item.id);if(at>=0)list[at]=item;else list.unshift(item);persist(list);editingId=item.id;toast(at>=0?'规则已更新':'规则已保存');showView('library')}
function renderLibrary(){const list=savedRules(),box=$('#libraryGrid');if(!box)return;if(!list.length){box.innerHTML='<div class="empty-library"><strong>还没有留存规则</strong><p>从一份正确样例开始生成第一条规则。</p></div>';return}box.innerHTML=list.map(r=>`<article class="rule-card"><div class="rule-card-top"><div><span class="step">RULE SET</span><h3>${escapeHtml(r.name)}</h3></div><button class="remove-rule" data-delete="${r.id}" type="button">×</button></div><p>${escapeHtml(r.desc||'暂无说明')}</p><div class="rule-card-meta"><span>${r.fields.length} 个字段</span><span>${r.fields.filter(f=>f.required).length} 个必填</span><span>${new Date(r.updatedAt).toLocaleDateString('zh-CN')}</span></div><div class="rule-card-actions"><button class="secondary-button" data-edit="${r.id}" type="button">打开编辑</button><button class="primary-button compact" data-use="${r.id}" type="button">校验报文</button></div></article>`).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>editRule(b.dataset.edit));$$('[data-use]').forEach(b=>b.onclick=()=>{showView('validate');$('#validateRule').value=b.dataset.use});$$('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('确定删除这条规则吗？'))persist(savedRules().filter(r=>r.id!==b.dataset.delete))})}
function editRule(id){const r=savedRules().find(x=>x.id===id);if(!r)return;editingId=id;fields=r.fields.map((f,i)=>({...f,id:`${Date.now()}-${i}`}));$('#ruleName').value=r.name;$('#ruleDesc').value=r.desc||'';$('#schemaInput').value=JSON.stringify(Object.fromEntries(r.fields.map(f=>[f.path,f.sample])),null,2);renderRules();showView('create');toast('已打开规则，可直接修改')}
function renderRuleSelect(){const sel=$('#validateRule');if(!sel)return;const current=sel.value,list=savedRules();sel.innerHTML=list.length?list.map(r=>`<option value="${r.id}">${escapeHtml(r.name)} · ${r.fields.length} 字段</option>`).join(''):'<option value="">请先创建规则</option>';if(list.some(r=>r.id===current))sel.value=current}
function getPath(obj,path){const keys=path.replace(/\[(\d+)\]/g,'.$1').split('.');let cur=obj;for(const k of keys){if(cur==null||!(k in Object(cur)))return{exists:false,value:undefined};cur=cur[k]}return{exists:true,value:cur}}
function validate(){const rule=savedRules().find(r=>r.id===$('#validateRule').value);if(!rule)return toast('请先创建并选择规则');let data;try{data=parseText($('#messageInput').value).data}catch(e){return toast(e.message)}lastResults=rule.fields.map(f=>{const got=getPath(data,f.path);let valid=true,reason='通过';if(!got.exists||got.value===''||got.value==null){valid=!f.required;reason=f.required?'缺少必填字段':'可选字段为空'}else{try{const pattern=f.pattern||formats[f.format]?.pattern||'.*';valid=new RegExp(pattern).test(String(got.value));reason=valid?'格式正确':(formats[f.format]?.message||'不符合规则')}catch{valid=false;reason='规则正则表达式无效'}}return{...f,value:got.value,exists:got.exists,valid,reason}});errorsOnly=false;renderResults();$('#messageStatus').textContent=`已校验 ${lastResults.length} 个字段`}
function renderResults(){const box=$('#validationResults');if(!lastResults.length)return;const badCount=lastResults.filter(x=>!x.valid).length,pass=lastResults.length-badCount;$('#summaryPills').innerHTML=`<span class="pass">✓ ${pass} 通过</span><span class="fail">× ${badCount} 异常</span><span>${lastResults.length} 字段</span>`;box.innerHTML=lastResults.map(x=>`<div class="check-row ${x.valid?'':'invalid'} ${errorsOnly&&x.valid?'filtered':''}"><span class="check-icon">${x.valid?'✓':'!'}</span><code class="check-path">${escapeHtml(x.path)}</code><span class="check-value" title="${escapeHtml(String(x.value??''))}">${x.exists?escapeHtml(JSON.stringify(x.value)):'— 未提供 —'}</span><span class="check-reason">${escapeHtml(x.reason)} · ${escapeHtml(formats[x.format]?.label||x.format)}</span></div>`).join('');$('#onlyErrors').textContent=errorsOnly?'显示全部':'仅看异常'}
function showView(name){$$('.rule-view').forEach(v=>v.hidden=v.id!==`${name}View`);$$('.flow-tab').forEach(t=>t.classList.toggle('active',t.dataset.view===name));if(name==='library')renderLibrary();if(name==='validate')renderRuleSelect();scrollTo({top:0,behavior:'smooth'})}
function readFile(file,target,callback){if(!file)return;if(file.size>5*1024*1024)return toast('文件不能超过 5MB');const reader=new FileReader();reader.onload=()=>{target.value=reader.result;callback?.(reader.result)};reader.onerror=()=>toast('文件读取失败');reader.readAsText(file)}
function wireDrop(zone,input,target,callback){zone.ondragover=e=>{e.preventDefault();zone.classList.add('dragging')};zone.ondragleave=()=>zone.classList.remove('dragging');zone.ondrop=e=>{e.preventDefault();zone.classList.remove('dragging');readFile(e.dataTransfer.files[0],target,callback)};input.onchange=()=>readFile(input.files[0],target,callback)}
$$('.flow-tab').forEach(t=>t.onclick=()=>showView(t.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));
$('#analyzeButton').onclick=()=>{try{analyze($('#schemaInput').value)}catch(e){toast(e.message)}};$('#loadSample').onclick=()=>{$('#schemaInput').value=JSON.stringify(sample,null,2);analyze($('#schemaInput').value)};$('#saveRule').onclick=saveRule;$('#validateButton').onclick=validate;$('#badSample').onclick=()=>{$('#messageInput').value=JSON.stringify(bad,null,2);$('#messageStatus').textContent='已载入包含 6 处异常的示例'};$('#onlyErrors').onclick=()=>{errorsOnly=!errorsOnly;renderResults()};
wireDrop($('#schemaDrop'),$('#schemaFile'),$('#schemaInput'),text=>{try{analyze(text)}catch(e){toast(e.message)}});wireDrop($('#messageDrop'),$('#messageFile'),$('#messageInput'),()=>$('#messageStatus').textContent='文件已读取，等待校验');
$('#themeButton').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('json-lens-theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('json-lens-theme')==='dark'||(!localStorage.getItem('json-lens-theme')&&matchMedia('(prefers-color-scheme: dark)').matches))document.body.classList.add('dark');
updateRuleCount();
